# Project Title

Financial Risk

# Domain

Finance

# Objective

1. To identify meaningful patterns, trends, and insights in financial transaction data using Exploratory Data Analysis (EDA).

2. To clean, transform, and preprocess the dataset by handling missing values, duplicates, and ensuring overall data quality..

3. To analyze customer financial behavior, including transaction patterns, account balance trends, and risk level distribution.

4. To examine the relationship between key variables such as credit score, loan amount, transaction amount, and risk classification.

5. To create clear and informative visualizations using Python libraries such as Matplotlib and Seaborn for better data interpretation.

6. To derive actionable insights to support risk management, customer segmentation, and data-driven decision-making in the banking domain.

# Outcome

The project helps uncover key patterns, trends, and hidden insights from the dataset. The analysis provides a clear understanding of the data and supports decision-making with evidence-based findings.

# Dataset Information

Source: https://www.kaggle.com/datasets/txtpwsss/dirty-financial-risk-dataset

Year / Timeline: Data collected during 2023

Dataset Description:

The dataset contains financial transaction records of bank customers. It includes details such as customer information, transaction data, credit details, and market indicators used for financial analysis and risk assessment.

Name : It represents the name of the customer.

Age : It indicates the age of the customer.

Gender : It specifies the gender of the customer.

Account Balance : It shows the available balance in the customer’s account.

Transaction Amount : It represents the amount involved in each transaction.

Transaction Type : It indicates whether the transaction is a credit or debit.

Credit Score : It represents the creditworthiness of the customer.

Risk Level : It classifies customers into low, medium, or high risk.

Loan Amount : It indicates the loan amount taken by the customer.

Interest Rate : It shows the interest rate applied to the loan or financial product.

Inflation Rate : It represents the economic inflation rate at the time of transaction.

Market Volatility Index : It indicates the level of market fluctuations.

Timestamp : It shows the date and time of the transaction.

Device Type : It represents the device used for the transaction (mobile/desktop).

Location : It indicates the customer’s geographical location.

# Type of Analysis

**Descriptive Analysis (summarizing the dataset)**

In this project, descriptive analysis was performed to summarize the financial dataset. We analyzed key variables such as transaction amount, account balance, credit score, and risk level. Data was grouped based on transaction type and risk level to understand distribution patterns. We also examined average values of market indicators like interest rate, inflation rate, and market volatility index. This helped identify common transaction behaviors, customer risk segments, and overall financial trends.

**Diagnostic Analysis (finding reasons behind patterns)**

Diagnostic analysis was conducted to identify factors influencing financial risk and transaction behavior. We analyzed the relationship between credit score and risk level, transaction amount and account balance, and market volatility with investment duration. Additionally, we examined how device usage metrics (CPU and memory usage) relate to user activity patterns. This helped identify key drivers affecting risk classification and customer financial behavior.

**Predictive Analysis (optional if forecasting required using basic stats)**

Predictive analysis was performed by analyzing trends over time using the timestamp column. We studied patterns in transaction amounts and risk levels across different time periods. Based on historical data, we identified periods with higher financial activity and potential risk fluctuations. This helps in forecasting future transaction trends and anticipating high-risk scenarios

**Prescriptive Analysis (recommendations for business decisions)**

Based on the analysis, several recommendations were provided. It is suggested to closely monitor users with low credit scores and high transaction amounts, as they may indicate higher risk. Financial institutions can optimize decision-making by considering market indicators like inflation and interest rates. Additionally, improving monitoring systems using device usage patterns can help detect unusual activities. Businesses can also implement targeted strategies for different risk-level customers to improve financial stability and reduce potential losses.

# Stages for DA Project

## Stage 1 – Problem Definition and Dataset Selection

**Define the business problem and expected outcome**

Financial institutions handle a large number of transactions daily, making it difficult to manually identify fraudulent or high-risk activities. There is a need to analyze transaction data to detect unusual patterns and reduce financial risk.

**Expected Outcome:**

Identify suspicious or abnormal transactions
Understand customer spending behavior
Detect potential fraud patterns
Provide insights to improve financial decision-making

Choose dataset and explain its source, size, and features

Import libraries, load dataset

Dataset description (rows, columns, features)

Initial EDA (head, info, describe, shape, null checks, duplicate check)

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('dirty_financial_dataset.csv')
df.head()

,timestamp,user_id,transaction_amount,transaction_type,account_balance,market_volatility_index,interest_rate,inflation_rate,stock_index_change,investment_duration_days,credit_score,device_cpu_usage,device_memory_usage,risk_level
0,2023-01-20 22:48,U3733,1410.55,deposit,14997.29,19.82,4.14,1.70,-3.27,73.00,538,18.50,41.30,2.00
1,2023-06-25 19:33,U3980,1807.7,transfer,12306.65,20.68,2.35,1.14,-2.97,202.00,675,31.60,76.50,1.00
2,2023.08-22,U9587,469.92,deposit,8270.87,24.03,2.06,2.44,-1.74,91.00,710,36.00,39.90,1.00
3,2023-11-04 22:25,U2214,293.19,deposit,9862.62,34.22,2.77,3.47,-0.98,175.00,392,87.10,94.10,1.00
4,2023-06-20 22:28,U4604,758.05,withdrawal,12114.18,28.04,4.42,1.85,-1.08,211.00,431,84.20,62.00,2.00

In [ ]:
df.shape

(3275, 14)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3275 entries, 0 to 3274
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   timestamp                 3275 non-null   object
 1   user_id                   3275 non-null   object
 2   transaction_amount        3243 non-null   object
 3   transaction_type          3275 non-null   object
 4   account_balance           3275 non-null   object
 5   market_volatility_index   3275 non-null   float64
 6   interest_rate             3275 non-null   float64
 7   inflation_rate            3275 non-null   float64
 8   stock_index_change        3275 non-null   float64
 9   investment_duration_days  3275 non-null   float64
 10  credit_score              3275 non-null   int64
 11  device_cpu_usage          3275 non-null   float64
 12  device_memory_usage       3275 non-null   float64
 13  risk_level                3275 non-null   float64
dtypes: float64(8), int64(1), object(5)
memory usage: 358.3+ KB

In [ ]:
df.head()

,timestamp,user_id,transaction_amount,transaction_type,account_balance,market_volatility_index,interest_rate,inflation_rate,stock_index_change,investment_duration_days,credit_score,device_cpu_usage,device_memory_usage,risk_level
0,2023-01-20 22:48,U3733,1410.55,deposit,14997.29,19.82,4.14,1.70,-3.27,73.00,538,18.50,41.30,2.00
1,2023-06-25 19:33,U3980,1807.7,transfer,12306.65,20.68,2.35,1.14,-2.97,202.00,675,31.60,76.50,1.00
2,2023.08-22,U9587,469.92,deposit,8270.87,24.03,2.06,2.44,-1.74,91.00,710,36.00,39.90,1.00
3,2023-11-04 22:25,U2214,293.19,deposit,9862.62,34.22,2.77,3.47,-0.98,175.00,392,87.10,94.10,1.00
4,2023-06-20 22:28,U4604,758.05,withdrawal,12114.18,28.04,4.42,1.85,-1.08,211.00,431,84.20,62.00,2.00

In [ ]:
df.tail()

,timestamp,user_id,transaction_amount,transaction_type,account_balance,market_volatility_index,interest_rate,inflation_rate,stock_index_change,investment_duration_days,credit_score,device_cpu_usage,device_memory_usage,risk_level
3270,2023-08-19 1:16,U8338,1119.34,withdrawal,3297.86,36.26,3.10,4.07,0.66,325.00,689,67.90,78.40,0.00
3271,2023-04-21 13:40,U5414,1303.5,withdrawal,11479.81,20.16,2.25,3.69,0.00,160.00,524,77.00,76.30,1.00
3272,2023-06-07 19:52,U7985,1299.24,transfer,11451.17,35.25,1.58,1.67,-1.85,125.00,673,57.60,35.10,1.00
3273,2023-09-28 4:46,U6336,117.2,transfer,7176.52,15.60,1.69,1.83,-0.96,315.00,793,27.10,15.90,0.00
3274,2023-02-23 12:26,U5969,1364.33,deposit,9599.77,30.83,2.42,1.95,-0.13,302.00,435,66.40,91.10,1.00

In [ ]:
df.describe()

,market_volatility_index,interest_rate,inflation_rate,stock_index_change,investment_duration_days,credit_score,device_cpu_usage,device_memory_usage,risk_level
count,3275.00,3275.00,3275.00,3275.00,3275.00,3275.00,3275.00,3275.00,3275.00
mean,24.92,2.77,3.48,-0.02,184.78,578.51,50.66,54.73,0.84
std,8.66,1.29,1.42,1.48,104.31,159.22,22.95,23.10,0.69
min,10.01,0.50,1.00,-5.13,7.00,300.00,10.10,15.00,0.00
25%,17.61,1.65,2.25,-1.02,94.00,441.00,31.30,34.80,0.00
50%,24.92,2.80,3.45,0.00,185.00,582.00,50.80,55.20,1.00
75%,32.30,3.88,4.66,0.99,274.00,714.50,70.50,74.80,1.00
max,39.99,5.00,5.99,5.06,364.00,849.00,90.00,95.00,2.00

In [ ]:
df.columns

Index(['timestamp', 'user_id', 'transaction_amount', 'transaction_type',
       'account_balance', 'market_volatility_index', 'interest_rate',
       'inflation_rate', 'stock_index_change', 'investment_duration_days',
       'credit_score', 'device_cpu_usage', 'device_memory_usage',
       'risk_level'],
      dtype='object')

In [ ]:
df.size

45850

In [ ]:
df.dtypes

timestamp                    object
user_id                      object
transaction_amount           object
transaction_type             object
account_balance              object
market_volatility_index     float64
interest_rate               float64
inflation_rate              float64
stock_index_change          float64
investment_duration_days    float64
credit_score                  int64
device_cpu_usage            float64
device_memory_usage         float64
risk_level                  float64
dtype: object

In [ ]:
df.isna().sum()

timestamp                    0
user_id                      0
transaction_amount          32
transaction_type             0
account_balance              0
market_volatility_index      0
interest_rate                0
inflation_rate               0
stock_index_change           0
investment_duration_days     0
credit_score                 0
device_cpu_usage             0
device_memory_usage          0
risk_level                   0
dtype: int64

In [ ]:
df.isnull().sum()

timestamp                    0
user_id                      0
transaction_amount          32
transaction_type             0
account_balance              0
market_volatility_index      0
interest_rate                0
inflation_rate               0
stock_index_change           0
investment_duration_days     0
credit_score                 0
device_cpu_usage             0
device_memory_usage          0
risk_level                   0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(7)

## Stage 2 – Data Cleaning and Pre-processing

Handle missing values (impute or drop)

Handle duplicates

Treat outliers if required

Check skewness and apply transformations

Convert data types if needed

Feature transformations (date parts, derived fields if required for analysis)

In [ ]:
df

,timestamp,user_id,transaction_amount,transaction_type,account_balance,market_volatility_index,interest_rate,inflation_rate,stock_index_change,investment_duration_days,credit_score,device_cpu_usage,device_memory_usage,risk_level
0,2023-01-20 22:48,U3733,1410.55,deposit,14997.29,19.82,4.14,1.70,-3.27,73.00,538,18.50,41.30,2.00
1,2023-06-25 19:33,U3980,1807.7,transfer,12306.65,20.68,2.35,1.14,-2.97,202.00,675,31.60,76.50,1.00
2,2023.08-22,U9587,469.92,deposit,8270.87,24.03,2.06,2.44,-1.74,91.00,710,36.00,39.90,1.00
3,2023-11-04 22:25,U2214,293.19,deposit,9862.62,34.22,2.77,3.47,-0.98,175.00,392,87.10,94.10,1.00
4,2023-06-20 22:28,U4604,758.05,withdrawal,12114.18,28.04,4.42,1.85,-1.08,211.00,431,84.20,62.00,2.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3269,2023-10-29 22:57,U6305,1865.11,deposit,15124.09,25.37,4.26,5.75,0.39,65.00,715,10.70,41.80,0.00
3270,2023-08-19 1:16,U8338,1119.34,withdrawal,3297.86,36.26,3.10,4.07,0.66,325.00,689,67.90,78.40,0.00
3271,2023-04-21 13:40,U5414,1303.5,withdrawal,11479.81,20.16,2.25,3.69,0.00,160.00,524,77.00,76.30,1.00
3273,2023-09-28 4:46,U6336,117.2,transfer,7176.52,15.60,1.69,1.83,-0.96,315.00,793,27.10,15.90,0.00
3274,2023-02-23 12:26,U5969,1364.33,deposit,9599.77,30.83,2.42,1.95,-0.13,302.00,435,66.40,91.10,1.00

To remove duplicates

In [ ]:
df = df.drop_duplicates(subset='user_id', keep='first')
df

,timestamp,user_id,transaction_amount,transaction_type,account_balance,market_volatility_index,interest_rate,inflation_rate,stock_index_change,investment_duration_days,credit_score,device_cpu_usage,device_memory_usage,risk_level
0,2023-01-20 22:48,U3733,1410.55,deposit,14997.29,19.82,4.14,1.70,-3.27,73.00,538,18.50,41.30,2.00
1,2023-06-25 19:33,U3980,1807.7,transfer,12306.65,20.68,2.35,1.14,-2.97,202.00,675,31.60,76.50,1.00
2,2023.08-22,U9587,469.92,deposit,8270.87,24.03,2.06,2.44,-1.74,91.00,710,36.00,39.90,1.00
3,2023-11-04 22:25,U2214,293.19,deposit,9862.62,34.22,2.77,3.47,-0.98,175.00,392,87.10,94.10,1.00
4,2023-06-20 22:28,U4604,758.05,withdrawal,12114.18,28.04,4.42,1.85,-1.08,211.00,431,84.20,62.00,2.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3269,2023-10-29 22:57,U6305,1865.11,deposit,15124.09,25.37,4.26,5.75,0.39,65.00,715,10.70,41.80,0.00
3270,2023-08-19 1:16,U8338,1119.34,withdrawal,3297.86,36.26,3.10,4.07,0.66,325.00,689,67.90,78.40,0.00
3271,2023-04-21 13:40,U5414,1303.5,withdrawal,11479.81,20.16,2.25,3.69,0.00,160.00,524,77.00,76.30,1.00
3273,2023-09-28 4:46,U6336,117.2,transfer,7176.52,15.60,1.69,1.83,-0.96,315.00,793,27.10,15.90,0.00
3274,2023-02-23 12:26,U5969,1364.33,deposit,9599.77,30.83,2.42,1.95,-0.13,302.00,435,66.40,91.10,1.00

To remove USD in transaction_amount

In [ ]:
df['transaction_amount'] = df['transaction_amount'].replace('[USD]', '', regex=True)
df

,timestamp,user_id,transaction_amount,transaction_type,account_balance,market_volatility_index,interest_rate,inflation_rate,stock_index_change,investment_duration_days,credit_score,device_cpu_usage,device_memory_usage,risk_level
0,2023-01-20 22:48,U3733,1410.55,deposit,14997.29,19.82,4.14,1.70,-3.27,73.00,538,18.50,41.30,2.00
1,2023-06-25 19:33,U3980,1807.7,transfer,12306.65,20.68,2.35,1.14,-2.97,202.00,675,31.60,76.50,1.00
2,2023.08-22,U9587,469.92,deposit,8270.87,24.03,2.06,2.44,-1.74,91.00,710,36.00,39.90,1.00
3,2023-11-04 22:25,U2214,293.19,deposit,9862.62,34.22,2.77,3.47,-0.98,175.00,392,87.10,94.10,1.00
4,2023-06-20 22:28,U4604,758.05,withdrawal,12114.18,28.04,4.42,1.85,-1.08,211.00,431,84.20,62.00,2.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3269,2023-10-29 22:57,U6305,1865.11,deposit,15124.09,25.37,4.26,5.75,0.39,65.00,715,10.70,41.80,0.00
3270,2023-08-19 1:16,U8338,1119.34,withdrawal,3297.86,36.26,3.10,4.07,0.66,325.00,689,67.90,78.40,0.00
3271,2023-04-21 13:40,U5414,1303.5,withdrawal,11479.81,20.16,2.25,3.69,0.00,160.00,524,77.00,76.30,1.00
3273,2023-09-28 4:46,U6336,117.2,transfer,7176.52,15.60,1.69,1.83,-0.96,315.00,793,27.10,15.90,0.00
3274,2023-02-23 12:26,U5969,1364.33,deposit,9599.77,30.83,2.42,1.95,-0.13,302.00,435,66.40,91.10,1.00

To change the Amount coloumn in numeric

In [ ]:
numeric_cols = ['transaction_amount','account_balance','market_volatility_index',
                'interest_rate','inflation_rate','stock_index_change',
                'investment_duration_days','credit_score',
                'device_cpu_usage','device_memory_usage']
df

,timestamp,user_id,transaction_amount,transaction_type,account_balance,market_volatility_index,interest_rate,inflation_rate,stock_index_change,investment_duration_days,credit_score,device_cpu_usage,device_memory_usage,risk_level
0,2023-01-20 22:48,U3733,1410.55,deposit,14997.29,19.82,4.14,1.70,-3.27,73.00,538,18.50,41.30,2.00
1,2023-06-25 19:33,U3980,1807.7,transfer,12306.65,20.68,2.35,1.14,-2.97,202.00,675,31.60,76.50,1.00
2,2023.08-22,U9587,469.92,deposit,8270.87,24.03,2.06,2.44,-1.74,91.00,710,36.00,39.90,1.00
3,2023-11-04 22:25,U2214,293.19,deposit,9862.62,34.22,2.77,3.47,-0.98,175.00,392,87.10,94.10,1.00
4,2023-06-20 22:28,U4604,758.05,withdrawal,12114.18,28.04,4.42,1.85,-1.08,211.00,431,84.20,62.00,2.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3269,2023-10-29 22:57,U6305,1865.11,deposit,15124.09,25.37,4.26,5.75,0.39,65.00,715,10.70,41.80,0.00
3270,2023-08-19 1:16,U8338,1119.34,withdrawal,3297.86,36.26,3.10,4.07,0.66,325.00,689,67.90,78.40,0.00
3271,2023-04-21 13:40,U5414,1303.5,withdrawal,11479.81,20.16,2.25,3.69,0.00,160.00,524,77.00,76.30,1.00
3273,2023-09-28 4:46,U6336,117.2,transfer,7176.52,15.60,1.69,1.83,-0.96,315.00,793,27.10,15.90,0.00
3274,2023-02-23 12:26,U5969,1364.33,deposit,9599.77,30.83,2.42,1.95,-0.13,302.00,435,66.40,91.10,1.00

To update the missing values in transaction_amount

To check the null

In [ ]:
df['transaction_amount'].isnull().sum()

np.int64(26)

In [ ]:
df['account_balance'] = df['account_balance'].replace('[$]', '', regex=True)
df

,timestamp,user_id,transaction_amount,transaction_type,account_balance,market_volatility_index,interest_rate,inflation_rate,stock_index_change,investment_duration_days,credit_score,device_cpu_usage,device_memory_usage,risk_level
0,2023-01-20 22:48,U3733,1410.55,deposit,14997.29,19.82,4.14,1.70,-3.27,73.00,538,18.50,41.30,2.00
1,2023-06-25 19:33,U3980,1807.7,transfer,12306.65,20.68,2.35,1.14,-2.97,202.00,675,31.60,76.50,1.00
2,2023.08-22,U9587,469.92,deposit,8270.87,24.03,2.06,2.44,-1.74,91.00,710,36.00,39.90,1.00
3,2023-11-04 22:25,U2214,293.19,deposit,9862.62,34.22,2.77,3.47,-0.98,175.00,392,87.10,94.10,1.00
4,2023-06-20 22:28,U4604,758.05,withdrawal,12114.18,28.04,4.42,1.85,-1.08,211.00,431,84.20,62.00,2.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3269,2023-10-29 22:57,U6305,1865.11,deposit,15124.09,25.37,4.26,5.75,0.39,65.00,715,10.70,41.80,0.00
3270,2023-08-19 1:16,U8338,1119.34,withdrawal,3297.86,36.26,3.10,4.07,0.66,325.00,689,67.90,78.40,0.00
3271,2023-04-21 13:40,U5414,1303.5,withdrawal,11479.81,20.16,2.25,3.69,0.00,160.00,524,77.00,76.30,1.00
3273,2023-09-28 4:46,U6336,117.2,transfer,7176.52,15.60,1.69,1.83,-0.96,315.00,793,27.10,15.90,0.00
3274,2023-02-23 12:26,U5969,1364.33,deposit,9599.77,30.83,2.42,1.95,-0.13,302.00,435,66.40,91.10,1.00

To change the decimals

In [ ]:
cols = ['transaction_amount','account_balance','market_volatility_index',
        'interest_rate','inflation_rate','stock_index_change',
        'investment_duration_days','credit_score',
        'device_cpu_usage','device_memory_usage']

df[cols] = df[cols].apply(lambda x: x.round(2))

df

,timestamp,user_id,transaction_amount,transaction_type,account_balance,market_volatility_index,interest_rate,inflation_rate,stock_index_change,investment_duration_days,credit_score,device_cpu_usage,device_memory_usage,risk_level
0,2023-01-20 22:48,U3733,1410.55,deposit,14997.29,19.82,4.14,1.70,-3.27,73.00,538,18.50,41.30,2.00
1,2023-06-25 19:33,U3980,1807.7,transfer,12306.65,20.68,2.35,1.14,-2.97,202.00,675,31.60,76.50,1.00
2,2023.08-22,U9587,469.92,deposit,8270.87,24.03,2.06,2.44,-1.74,91.00,710,36.00,39.90,1.00
3,2023-11-04 22:25,U2214,293.19,deposit,9862.62,34.22,2.77,3.47,-0.98,175.00,392,87.10,94.10,1.00
4,2023-06-20 22:28,U4604,758.05,withdrawal,12114.18,28.04,4.42,1.85,-1.08,211.00,431,84.20,62.00,2.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3269,2023-10-29 22:57,U6305,1865.11,deposit,15124.09,25.37,4.26,5.75,0.39,65.00,715,10.70,41.80,0.00
3270,2023-08-19 1:16,U8338,1119.34,withdrawal,3297.86,36.26,3.10,4.07,0.66,325.00,689,67.90,78.40,0.00
3271,2023-04-21 13:40,U5414,1303.5,withdrawal,11479.81,20.16,2.25,3.69,0.00,160.00,524,77.00,76.30,1.00
3273,2023-09-28 4:46,U6336,117.2,transfer,7176.52,15.60,1.69,1.83,-0.96,315.00,793,27.10,15.90,0.00
3274,2023-02-23 12:26,U5969,1364.33,deposit,9599.77,30.83,2.42,1.95,-0.13,302.00,435,66.40,91.10,1.00

To change the incosistance in transaction_type

In [ ]:
wrong_values = [
    'wdrialwhat','wlaridhtwa','lhdwraatwi','wldaithawr',
    'lhirtdwaaw','awwdilhart','widatrlhwa','aarwdtliwh','hltwaiawrd'
]

df.loc[df['transaction_type'].isin(wrong_values), 'transaction_type'] = 'Withdrawal'

df

,timestamp,user_id,transaction_amount,transaction_type,account_balance,market_volatility_index,interest_rate,inflation_rate,stock_index_change,investment_duration_days,credit_score,device_cpu_usage,device_memory_usage,risk_level
0,2023-01-20 22:48,U3733,1410.55,deposit,14997.29,19.82,4.14,1.70,-3.27,73.00,538,18.50,41.30,2.00
1,2023-06-25 19:33,U3980,1807.7,transfer,12306.65,20.68,2.35,1.14,-2.97,202.00,675,31.60,76.50,1.00
2,2023.08-22,U9587,469.92,deposit,8270.87,24.03,2.06,2.44,-1.74,91.00,710,36.00,39.90,1.00
3,2023-11-04 22:25,U2214,293.19,deposit,9862.62,34.22,2.77,3.47,-0.98,175.00,392,87.10,94.10,1.00
4,2023-06-20 22:28,U4604,758.05,withdrawal,12114.18,28.04,4.42,1.85,-1.08,211.00,431,84.20,62.00,2.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3269,2023-10-29 22:57,U6305,1865.11,deposit,15124.09,25.37,4.26,5.75,0.39,65.00,715,10.70,41.80,0.00
3270,2023-08-19 1:16,U8338,1119.34,withdrawal,3297.86,36.26,3.10,4.07,0.66,325.00,689,67.90,78.40,0.00
3271,2023-04-21 13:40,U5414,1303.5,withdrawal,11479.81,20.16,2.25,3.69,0.00,160.00,524,77.00,76.30,1.00
3273,2023-09-28 4:46,U6336,117.2,transfer,7176.52,15.60,1.69,1.83,-0.96,315.00,793,27.10,15.90,0.00
3274,2023-02-23 12:26,U5969,1364.33,deposit,9599.77,30.83,2.42,1.95,-0.13,302.00,435,66.40,91.10,1.00

In [ ]:
wrong_values = [
    'dopeits','topieds','poeitsd','eidstop', 'pditseo'

]

df.loc[df['transaction_type'].isin(wrong_values), 'transaction_type'] = 'Deposit'

df

,timestamp,user_id,transaction_amount,transaction_type,account_balance,market_volatility_index,interest_rate,inflation_rate,stock_index_change,investment_duration_days,credit_score,device_cpu_usage,device_memory_usage,risk_level
0,2023-01-20 22:48,U3733,1410.55,deposit,14997.29,19.82,4.14,1.70,-3.27,73.00,538,18.50,41.30,2.00
1,2023-06-25 19:33,U3980,1807.7,transfer,12306.65,20.68,2.35,1.14,-2.97,202.00,675,31.60,76.50,1.00
2,2023.08-22,U9587,469.92,deposit,8270.87,24.03,2.06,2.44,-1.74,91.00,710,36.00,39.90,1.00
3,2023-11-04 22:25,U2214,293.19,deposit,9862.62,34.22,2.77,3.47,-0.98,175.00,392,87.10,94.10,1.00
4,2023-06-20 22:28,U4604,758.05,withdrawal,12114.18,28.04,4.42,1.85,-1.08,211.00,431,84.20,62.00,2.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3269,2023-10-29 22:57,U6305,1865.11,deposit,15124.09,25.37,4.26,5.75,0.39,65.00,715,10.70,41.80,0.00
3270,2023-08-19 1:16,U8338,1119.34,withdrawal,3297.86,36.26,3.10,4.07,0.66,325.00,689,67.90,78.40,0.00
3271,2023-04-21 13:40,U5414,1303.5,withdrawal,11479.81,20.16,2.25,3.69,0.00,160.00,524,77.00,76.30,1.00
3273,2023-09-28 4:46,U6336,117.2,transfer,7176.52,15.60,1.69,1.83,-0.96,315.00,793,27.10,15.90,0.00
3274,2023-02-23 12:26,U5969,1364.33,deposit,9599.77,30.83,2.42,1.95,-0.13,302.00,435,66.40,91.10,1.00

In [ ]:
wrong_values = [
    'rsfenart','rsnaertf','esrtfarn','srfeatnr', 'eafnrstr','etfasnrr','tsrfenra'

]

df.loc[df['transaction_type'].isin(wrong_values), 'transaction_type'] = 'Transfer'

df

,timestamp,user_id,transaction_amount,transaction_type,account_balance,market_volatility_index,interest_rate,inflation_rate,stock_index_change,investment_duration_days,credit_score,device_cpu_usage,device_memory_usage,risk_level
0,2023-01-20 22:48,U3733,1410.55,deposit,14997.29,19.82,4.14,1.70,-3.27,73.00,538,18.50,41.30,2.00
1,2023-06-25 19:33,U3980,1807.7,transfer,12306.65,20.68,2.35,1.14,-2.97,202.00,675,31.60,76.50,1.00
2,2023.08-22,U9587,469.92,deposit,8270.87,24.03,2.06,2.44,-1.74,91.00,710,36.00,39.90,1.00
3,2023-11-04 22:25,U2214,293.19,deposit,9862.62,34.22,2.77,3.47,-0.98,175.00,392,87.10,94.10,1.00
4,2023-06-20 22:28,U4604,758.05,withdrawal,12114.18,28.04,4.42,1.85,-1.08,211.00,431,84.20,62.00,2.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3269,2023-10-29 22:57,U6305,1865.11,deposit,15124.09,25.37,4.26,5.75,0.39,65.00,715,10.70,41.80,0.00
3270,2023-08-19 1:16,U8338,1119.34,withdrawal,3297.86,36.26,3.10,4.07,0.66,325.00,689,67.90,78.40,0.00
3271,2023-04-21 13:40,U5414,1303.5,withdrawal,11479.81,20.16,2.25,3.69,0.00,160.00,524,77.00,76.30,1.00
3273,2023-09-28 4:46,U6336,117.2,transfer,7176.52,15.60,1.69,1.83,-0.96,315.00,793,27.10,15.90,0.00
3274,2023-02-23 12:26,U5969,1364.33,deposit,9599.77,30.83,2.42,1.95,-0.13,302.00,435,66.40,91.10,1.00

In [ ]:
wrong_values = [
    'meievtnsnt','vemtneistn','tneemsvnit','vsmnitetne', 'evinemntst','neminesvtt','eitvetnsnm','INVESTMENT'

]

df.loc[df['transaction_type'].isin(wrong_values), 'transaction_type'] = 'Investment'

df

,timestamp,user_id,transaction_amount,transaction_type,account_balance,market_volatility_index,interest_rate,inflation_rate,stock_index_change,investment_duration_days,credit_score,device_cpu_usage,device_memory_usage,risk_level
0,2023-01-20 22:48,U3733,1410.55,deposit,14997.29,19.82,4.14,1.70,-3.27,73.00,538,18.50,41.30,2.00
1,2023-06-25 19:33,U3980,1807.7,transfer,12306.65,20.68,2.35,1.14,-2.97,202.00,675,31.60,76.50,1.00
2,2023.08-22,U9587,469.92,deposit,8270.87,24.03,2.06,2.44,-1.74,91.00,710,36.00,39.90,1.00
3,2023-11-04 22:25,U2214,293.19,deposit,9862.62,34.22,2.77,3.47,-0.98,175.00,392,87.10,94.10,1.00
4,2023-06-20 22:28,U4604,758.05,withdrawal,12114.18,28.04,4.42,1.85,-1.08,211.00,431,84.20,62.00,2.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3269,2023-10-29 22:57,U6305,1865.11,deposit,15124.09,25.37,4.26,5.75,0.39,65.00,715,10.70,41.80,0.00
3270,2023-08-19 1:16,U8338,1119.34,withdrawal,3297.86,36.26,3.10,4.07,0.66,325.00,689,67.90,78.40,0.00
3271,2023-04-21 13:40,U5414,1303.5,withdrawal,11479.81,20.16,2.25,3.69,0.00,160.00,524,77.00,76.30,1.00
3273,2023-09-28 4:46,U6336,117.2,transfer,7176.52,15.60,1.69,1.83,-0.96,315.00,793,27.10,15.90,0.00
3274,2023-02-23 12:26,U5969,1364.33,deposit,9599.77,30.83,2.42,1.95,-0.13,302.00,435,66.40,91.10,1.00

To replace the with the help of mode in transaction type

In [ ]:
mode_val = df['transaction_type'].mode()[0]
df['transaction_type'] = df['transaction_type'].replace('INVALID_CATEGORY_DEFAULT', mode_val)

df

,timestamp,user_id,transaction_amount,transaction_type,account_balance,market_volatility_index,interest_rate,inflation_rate,stock_index_change,investment_duration_days,credit_score,device_cpu_usage,device_memory_usage,risk_level
0,2023-01-20 22:48,U3733,1410.55,deposit,14997.29,19.82,4.14,1.70,-3.27,73.00,538,18.50,41.30,2.00
1,2023-06-25 19:33,U3980,1807.7,transfer,12306.65,20.68,2.35,1.14,-2.97,202.00,675,31.60,76.50,1.00
2,2023.08-22,U9587,469.92,deposit,8270.87,24.03,2.06,2.44,-1.74,91.00,710,36.00,39.90,1.00
3,2023-11-04 22:25,U2214,293.19,deposit,9862.62,34.22,2.77,3.47,-0.98,175.00,392,87.10,94.10,1.00
4,2023-06-20 22:28,U4604,758.05,withdrawal,12114.18,28.04,4.42,1.85,-1.08,211.00,431,84.20,62.00,2.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3269,2023-10-29 22:57,U6305,1865.11,deposit,15124.09,25.37,4.26,5.75,0.39,65.00,715,10.70,41.80,0.00
3270,2023-08-19 1:16,U8338,1119.34,withdrawal,3297.86,36.26,3.10,4.07,0.66,325.00,689,67.90,78.40,0.00
3271,2023-04-21 13:40,U5414,1303.5,withdrawal,11479.81,20.16,2.25,3.69,0.00,160.00,524,77.00,76.30,1.00
3273,2023-09-28 4:46,U6336,117.2,transfer,7176.52,15.60,1.69,1.83,-0.96,315.00,793,27.10,15.90,0.00
3274,2023-02-23 12:26,U5969,1364.33,deposit,9599.77,30.83,2.42,1.95,-0.13,302.00,435,66.40,91.10,1.00

To Change the values as upper

In [ ]:
df['transaction_type'] = df['transaction_type'].str.upper()
df

,timestamp,user_id,transaction_amount,transaction_type,account_balance,market_volatility_index,interest_rate,inflation_rate,stock_index_change,investment_duration_days,credit_score,device_cpu_usage,device_memory_usage,risk_level
0,2023-01-20 22:48,U3733,1410.55,DEPOSIT,14997.29,19.82,4.14,1.70,-3.27,73.00,538,18.50,41.30,2.00
1,2023-06-25 19:33,U3980,1807.7,TRANSFER,12306.65,20.68,2.35,1.14,-2.97,202.00,675,31.60,76.50,1.00
2,2023.08-22,U9587,469.92,DEPOSIT,8270.87,24.03,2.06,2.44,-1.74,91.00,710,36.00,39.90,1.00
3,2023-11-04 22:25,U2214,293.19,DEPOSIT,9862.62,34.22,2.77,3.47,-0.98,175.00,392,87.10,94.10,1.00
4,2023-06-20 22:28,U4604,758.05,WITHDRAWAL,12114.18,28.04,4.42,1.85,-1.08,211.00,431,84.20,62.00,2.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3269,2023-10-29 22:57,U6305,1865.11,DEPOSIT,15124.09,25.37,4.26,5.75,0.39,65.00,715,10.70,41.80,0.00
3270,2023-08-19 1:16,U8338,1119.34,WITHDRAWAL,3297.86,36.26,3.10,4.07,0.66,325.00,689,67.90,78.40,0.00
3271,2023-04-21 13:40,U5414,1303.5,WITHDRAWAL,11479.81,20.16,2.25,3.69,0.00,160.00,524,77.00,76.30,1.00
3273,2023-09-28 4:46,U6336,117.2,TRANSFER,7176.52,15.60,1.69,1.83,-0.96,315.00,793,27.10,15.90,0.00
3274,2023-02-23 12:26,U5969,1364.33,DEPOSIT,9599.77,30.83,2.42,1.95,-0.13,302.00,435,66.40,91.10,1.00

To change the u as U and remove the - in user_id

In [ ]:
df['user_id'] = df['user_id'].str.upper()
df['user_id'] = df['user_id'].str.replace('-', '', regex=False)
df

,timestamp,user_id,transaction_amount,transaction_type,account_balance,market_volatility_index,interest_rate,inflation_rate,stock_index_change,investment_duration_days,credit_score,device_cpu_usage,device_memory_usage,risk_level
0,2023-01-20 22:48,U3733,1410.55,DEPOSIT,14997.29,19.82,4.14,1.70,-3.27,73.00,538,18.50,41.30,2.00
1,2023-06-25 19:33,U3980,1807.7,TRANSFER,12306.65,20.68,2.35,1.14,-2.97,202.00,675,31.60,76.50,1.00
2,2023.08-22,U9587,469.92,DEPOSIT,8270.87,24.03,2.06,2.44,-1.74,91.00,710,36.00,39.90,1.00
3,2023-11-04 22:25,U2214,293.19,DEPOSIT,9862.62,34.22,2.77,3.47,-0.98,175.00,392,87.10,94.10,1.00
4,2023-06-20 22:28,U4604,758.05,WITHDRAWAL,12114.18,28.04,4.42,1.85,-1.08,211.00,431,84.20,62.00,2.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3269,2023-10-29 22:57,U6305,1865.11,DEPOSIT,15124.09,25.37,4.26,5.75,0.39,65.00,715,10.70,41.80,0.00
3270,2023-08-19 1:16,U8338,1119.34,WITHDRAWAL,3297.86,36.26,3.10,4.07,0.66,325.00,689,67.90,78.40,0.00
3271,2023-04-21 13:40,U5414,1303.5,WITHDRAWAL,11479.81,20.16,2.25,3.69,0.00,160.00,524,77.00,76.30,1.00
3273,2023-09-28 4:46,U6336,117.2,TRANSFER,7176.52,15.60,1.69,1.83,-0.96,315.00,793,27.10,15.90,0.00
3274,2023-02-23 12:26,U5969,1364.33,DEPOSIT,9599.77,30.83,2.42,1.95,-0.13,302.00,435,66.40,91.10,1.00

In [ ]:
df

,timestamp,user_id,transaction_amount,transaction_type,account_balance,market_volatility_index,interest_rate,inflation_rate,stock_index_change,investment_duration_days,credit_score,device_cpu_usage,device_memory_usage,risk_level
0,2023-01-20 22:48,U3733,1410.55,DEPOSIT,14997.29,19.82,4.14,1.70,-3.27,73.00,538,18.50,41.30,2.00
1,2023-06-25 19:33,U3980,1807.7,TRANSFER,12306.65,20.68,2.35,1.14,-2.97,202.00,675,31.60,76.50,1.00
2,2023.08-22,U9587,469.92,DEPOSIT,8270.87,24.03,2.06,2.44,-1.74,91.00,710,36.00,39.90,1.00
3,2023-11-04 22:25,U2214,293.19,DEPOSIT,9862.62,34.22,2.77,3.47,-0.98,175.00,392,87.10,94.10,1.00
4,2023-06-20 22:28,U4604,758.05,WITHDRAWAL,12114.18,28.04,4.42,1.85,-1.08,211.00,431,84.20,62.00,2.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3269,2023-10-29 22:57,U6305,1865.11,DEPOSIT,15124.09,25.37,4.26,5.75,0.39,65.00,715,10.70,41.80,0.00
3270,2023-08-19 1:16,U8338,1119.34,WITHDRAWAL,3297.86,36.26,3.10,4.07,0.66,325.00,689,67.90,78.40,0.00
3271,2023-04-21 13:40,U5414,1303.5,WITHDRAWAL,11479.81,20.16,2.25,3.69,0.00,160.00,524,77.00,76.30,1.00
3273,2023-09-28 4:46,U6336,117.2,TRANSFER,7176.52,15.60,1.69,1.83,-0.96,315.00,793,27.10,15.90,0.00
3274,2023-02-23 12:26,U5969,1364.33,DEPOSIT,9599.77,30.83,2.42,1.95,-0.13,302.00,435,66.40,91.10,1.00

Corrected the incositance in timestamp column and seprated the date and time

In [ ]:
df['timestamp'] = pd.to_datetime(df['timestamp'], errors='coerce')
mode_time = df['timestamp'].mode()[0]
df['timestamp'] = df['timestamp'].fillna(mode_time)

df

,timestamp,user_id,transaction_amount,transaction_type,account_balance,market_volatility_index,interest_rate,inflation_rate,stock_index_change,investment_duration_days,credit_score,device_cpu_usage,device_memory_usage,risk_level
0,2023-01-20 22:48:00,U3733,1410.55,DEPOSIT,14997.29,19.82,4.14,1.70,-3.27,73.00,538,18.50,41.30,2.00
1,2023-06-25 19:33:00,U3980,1807.7,TRANSFER,12306.65,20.68,2.35,1.14,-2.97,202.00,675,31.60,76.50,1.00
2,2023-01-12 20:36:00,U9587,469.92,DEPOSIT,8270.87,24.03,2.06,2.44,-1.74,91.00,710,36.00,39.90,1.00
3,2023-11-04 22:25:00,U2214,293.19,DEPOSIT,9862.62,34.22,2.77,3.47,-0.98,175.00,392,87.10,94.10,1.00
4,2023-06-20 22:28:00,U4604,758.05,WITHDRAWAL,12114.18,28.04,4.42,1.85,-1.08,211.00,431,84.20,62.00,2.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3269,2023-10-29 22:57:00,U6305,1865.11,DEPOSIT,15124.09,25.37,4.26,5.75,0.39,65.00,715,10.70,41.80,0.00
3270,2023-08-19 01:16:00,U8338,1119.34,WITHDRAWAL,3297.86,36.26,3.10,4.07,0.66,325.00,689,67.90,78.40,0.00
3271,2023-04-21 13:40:00,U5414,1303.5,WITHDRAWAL,11479.81,20.16,2.25,3.69,0.00,160.00,524,77.00,76.30,1.00
3273,2023-09-28 04:46:00,U6336,117.2,TRANSFER,7176.52,15.60,1.69,1.83,-0.96,315.00,793,27.10,15.90,0.00
3274,2023-02-23 12:26:00,U5969,1364.33,DEPOSIT,9599.77,30.83,2.42,1.95,-0.13,302.00,435,66.40,91.10,1.00

In [ ]:
df['Date'] = df['timestamp'].dt.date
df['Time'] = df['timestamp'].dt.time
df

,user_id,transaction_amount,transaction_type,account_balance,market_volatility_index,interest_rate,inflation_rate,stock_index_change,investment_duration_days,credit_score,device_cpu_usage,device_memory_usage,risk_level,Date,Time
0,U3733,1410.55,DEPOSIT,14997.29,19.82,4.14,1.70,-3.27,73.00,538,18.50,41.30,2.00,2023-01-20,22:48:00
1,U3980,1807.7,TRANSFER,12306.65,20.68,2.35,1.14,-2.97,202.00,675,31.60,76.50,1.00,2023-06-25,19:33:00
2,U9587,469.92,DEPOSIT,8270.87,24.03,2.06,2.44,-1.74,91.00,710,36.00,39.90,1.00,2023-01-12,20:36:00
3,U2214,293.19,DEPOSIT,9862.62,34.22,2.77,3.47,-0.98,175.00,392,87.10,94.10,1.00,2023-11-04,22:25:00
4,U4604,758.05,WITHDRAWAL,12114.18,28.04,4.42,1.85,-1.08,211.00,431,84.20,62.00,2.00,2023-06-20,22:28:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3269,U6305,1865.11,DEPOSIT,15124.09,25.37,4.26,5.75,0.39,65.00,715,10.70,41.80,0.00,2023-10-29,22:57:00
3270,U8338,1119.34,WITHDRAWAL,3297.86,36.26,3.10,4.07,0.66,325.00,689,67.90,78.40,0.00,2023-08-19,01:16:00
3271,U5414,1303.5,WITHDRAWAL,11479.81,20.16,2.25,3.69,0.00,160.00,524,77.00,76.30,1.00,2023-04-21,13:40:00
3273,U6336,117.2,TRANSFER,7176.52,15.60,1.69,1.83,-0.96,315.00,793,27.10,15.90,0.00,2023-09-28,04:46:00
3274,U5969,1364.33,DEPOSIT,9599.77,30.83,2.42,1.95,-0.13,302.00,435,66.40,91.10,1.00,2023-02-23,12:26:00

In [ ]:
cols = ['Date','Time'] + [col for col in df.columns if col not in ['Date','Time']]
df = df[cols]

In [ ]:
df

,Date,Time,user_id,transaction_amount,transaction_type,account_balance,market_volatility_index,interest_rate,inflation_rate,stock_index_change,investment_duration_days,credit_score,device_cpu_usage,device_memory_usage,risk_level
0,2023-01-20,22:48:00,U3733,1410.55,DEPOSIT,14997.29,19.82,4.14,1.70,-3.27,73.00,538,18.50,41.30,2.00
1,2023-06-25,19:33:00,U3980,1807.7,TRANSFER,12306.65,20.68,2.35,1.14,-2.97,202.00,675,31.60,76.50,1.00
2,2023-01-12,20:36:00,U9587,469.92,DEPOSIT,8270.87,24.03,2.06,2.44,-1.74,91.00,710,36.00,39.90,1.00
3,2023-11-04,22:25:00,U2214,293.19,DEPOSIT,9862.62,34.22,2.77,3.47,-0.98,175.00,392,87.10,94.10,1.00
4,2023-06-20,22:28:00,U4604,758.05,WITHDRAWAL,12114.18,28.04,4.42,1.85,-1.08,211.00,431,84.20,62.00,2.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3269,2023-10-29,22:57:00,U6305,1865.11,DEPOSIT,15124.09,25.37,4.26,5.75,0.39,65.00,715,10.70,41.80,0.00
3270,2023-08-19,01:16:00,U8338,1119.34,WITHDRAWAL,3297.86,36.26,3.10,4.07,0.66,325.00,689,67.90,78.40,0.00
3271,2023-04-21,13:40:00,U5414,1303.5,WITHDRAWAL,11479.81,20.16,2.25,3.69,0.00,160.00,524,77.00,76.30,1.00
3273,2023-09-28,04:46:00,U6336,117.2,TRANSFER,7176.52,15.60,1.69,1.83,-0.96,315.00,793,27.10,15.90,0.00
3274,2023-02-23,12:26:00,U5969,1364.33,DEPOSIT,9599.77,30.83,2.42,1.95,-0.13,302.00,435,66.40,91.10,1.00

Corrected the proper format in heading

In [ ]:
df.columns = df.columns.str.title()
df.head()

,Date,Time,User_Id,Transaction_Amount,Transaction_Type,Account_Balance,Market_Volatility_Index,Interest_Rate,Inflation_Rate,Stock_Index_Change,Investment_Duration_Days,Credit_Score,Device_Cpu_Usage,Device_Memory_Usage,Risk_Level
0,2023-01-20,22:48:00,U3733,1410.55,DEPOSIT,14997.29,19.82,4.14,1.70,-3.27,73.00,538,18.50,41.30,2.00
1,2023-06-25,19:33:00,U3980,1807.7,TRANSFER,12306.65,20.68,2.35,1.14,-2.97,202.00,675,31.60,76.50,1.00
2,2023-01-12,20:36:00,U9587,469.92,DEPOSIT,8270.87,24.03,2.06,2.44,-1.74,91.00,710,36.00,39.90,1.00
3,2023-11-04,22:25:00,U2214,293.19,DEPOSIT,9862.62,34.22,2.77,3.47,-0.98,175.00,392,87.10,94.10,1.00
4,2023-06-20,22:28:00,U4604,758.05,WITHDRAWAL,12114.18,28.04,4.42,1.85,-1.08,211.00,431,84.20,62.00,2.00

In [ ]:
df.to_csv('cleaned_datafinalset.csv', index=False)

## Stage 3 – EDA and Visualizations

Univariate Analysis → distribution of single variables (countplot, histogram, boxplot)

Bivariate Analysis → relation between two variables (scatterplot, barplot, correlation heatmap)

Multivariate Analysis → relation among 3+ variables (pairplot, grouped analysis, pivot tables, advanced plots)

Interpretation MUST with every visualization

Focus on business story not just charts

Each chart must be in seperate cells.

In [ ]:
# your chart here
# If you want more cells, you can add or less cells you can remove, but dont change the structure.

## Interpretation of your above chart

Explain the Chart.

What is it saying?

What features you used?

From this what you are showing us?

In [ ]:
# your code here
# If you want more cells, you can add or less cells you can remove, but dont change the structure.

## Interpretation of your above chart

Explain the Chart.

What is it saying?

What features you used?

From this what you are showing us?

In [ ]:
# your code here
# If you want more cells, you can add or less cells you can remove, but dont change the structure.

## Interpretation of your above chart

Explain the Chart.

What is it saying?

What features you used?

From this what you are showing us?

In [ ]:
# your code here
# If you want more cells, you can add or less cells you can remove, but dont change the structure.

## Interpretation of your above chart

Explain the Chart.

What is it saying?

What features you used?

From this what you are showing us?

In [ ]:
# your code here
# If you want more cells, you can add or less cells you can remove, but dont change the structure.

## Interpretation of your above chart

Explain the Chart.

What is it saying?

What features you used?

From this what you are showing us?

## Stage 4 – Documentation, Insights and Presentation

Show a dashboard aligning all the charts in powerbi by connecting python in PowerBI

Summarize findings in plain English (what do the patterns mean)

Highlight 3–5 key insights (trends, anomalies, correlations)

Provide recommendations for business or decision-making

Explain the FINAL STORY WITH THE DASHBOARD

Create a PDF pasting your DASHBOARD, explaining all the above mentioned concepts and submit it

In [ ]:
# your stage 4 pdf Link

'''
step1 --> Create a docs that should have all the above mentioned
step2 --> Save it as "Stage4_doc"
Step3 --> Download it as PDF
step4 --> Upload the pdf in your drive
step5 --> Right click on your pdf in drive
step6 --> click share and change access into anyone with the link (Viewer)
step7 --> click copy link and paste it here...
You are done.
'''